#!/bin/sh
set -e

echo "${PGHBA}" > /app/cnf/pg_hba.conf
echo "${USERLIST}" > /app/cnf/userlist.txt
echo "${CONFIG}" > /app/cnf/pgbouncer.ini

if [ -z "$TLSCRT" ] && [ -z "$TLSKEY" ]; then
  fqdn="${FQDN:-autogenerated-selfsigned-cert}"
  openssl req -x509 -nodes -days 3650 -newkey rsa:4096 -keyout tls.key -out tls.crt -subj "/CN=$fqdn" -addext "subjectAltName = DNS:$fqdn"
  mv tls.key  tls.crt /app/certs/
else
  echo "$TLSCRT" > /app/certs/tls.crt
  echo "$TLSKEY" > /app/certs/tls.key
fi

echo "Starting pgbouncer ..."

/app/bin/pgbouncer /app/cnf/pgbouncer.ini
