---
apiVersion: v1
data:
  # GOOSE_DRIVER: sqlite3
  GOOSE_DRIVER: postgres
  # GOOSE_MIGRATION_DIR: migrations/sqlite3 
  GOOSE_MIGRATION_DIR: migrations/postgres

  C: US
  S: Utah
  L: Lehi
  O: ExampleOrg
  OU: example.org
  ROOT_CN: ExampleOrg-RootCA1
  INTERMEDIATE_CN: ExampleOrg-ICA1a
  HOST_INTERMEDIATE_CN: ExampleOrg-ICA2aHost
  CLIENT_INTERMEDIATE_CN: ExampleOrg-ICA3aClient
  # CLIENT_INTERMEDIATE_CN="${ORG_NAME} Server R1"

  O: EXAMPLE
  ALGO: rsa
  ALGOSIZE: "4096"
  INTERMEDIATE_EXPIRE_HOURS: 43800h
  ROOT_EXPIRE_HOURS: 87600h
  HOST_EXPIRE_HOURS: 8760h
  DEFAULT_EXPIRE_HOURS: 8760h
  SERVER_EXPIRE_HOURS: 8760h
  CLIENT_EXPIRE_HOURS: 8760h
  OSCP_EXPIRE_HOURS: 26280h
  PEER_EXPIRE_HOURS: 8760h
  # OUT_DIR=cfssl-ca
  OUT_DIR: .

kind: ConfigMap
metadata:
  name: cfssl-env
