services:
  db:
    image: uvoo/postgresql18:latest
    container_name: pg18
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: app
      POSTGRES_INITDB_ARGS: "--auth-local=trust --auth-host=scram-sha-256"
      # _POSTGRES_EXTRA_CONFIG: |
      #   listen_addresses='*'
      #   shared_preload_libraries = 'timescaledb,pg_cron'
      #   cron.database_name = 'app'
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    command: >
      postgres
      -c listen_addresses='*'
      -c shared_preload_libraries='timescaledb,pg_cron'
      -c cron.database_name='app'

volumes:
  pgdata:
