services:
  db:
    build: .
    image: my-postgres:18
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: app
      POSTGRES_INITDB_ARGS: "--data-checksums --auth-host=scram-sha-256"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    secrets:
      - postgres_password
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  pgdata:
